title: "My Retro Site"
description: "Press START to continue..."
theme: minima  # <-- default GitHub theme (easy to override)

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: assets/css
